language: python
python:
- '2.7'
- pypy
before_install:
- cp hellosign/tests/test_helper.sample.py hellosign/tests/test_helper.py
install:
- pip install -e . --use-mirrors
- pip install -r test_requirements.txt --use-mirrors
script:
  - nosetests --with-coverage --cover-package=hellosign --include=hellosign/tests/unit_tests/* --include=hellosign/tests/functional_tests/*
after_success:
- coveralls
env:
  global:
  - secure: CYSSycNhQ7/3RCwQvHgyilTLnPlCRTlnoXsSGMz3eAdkRLpEdF4zwO0RTSm+ZsUudBD0CBssejSHfrvWOSJVIdyEbHYnjnfKyByXYEe1TqRvRp5RMNWQl25aCJfmNicJX5o0iRiEAnoPff+AGHlS5BGzoM54hT61D8UeASeDHxc=
  - secure: lN5c/VlRKpgADCxpeOT7MtXfHEfcTduRkv6Py/TgKE+Wnep5zFJhm1cr1aBRIeKIdyChg0UGkfyGfDNiYCgBH22WdsotU68V+OtH5n4ykfwx6uxwzMAtAhRqwfedr20/rMYqY1yMNrWeLfuEY0z9uDHnXREMMKXzgTQfQ9cZOrk=
  - secure: S5q+K1ZhX1x5NrFHBiundMxA1RVmy83KXw5QrXmIMEXPL7PYLAykte6kEdqHZ/+MFFEjcuLpFbMrTxJvvk6LgQfXJi25gL88CuYH2MNFOTRXBQ5GNhgzrv0RGI9rTTKsbe1KE7mgCIiLX8/wyFMMm9tUN4a3MjGPgmlX4vhCwwo=
